import os
from pathlib import Path
from contextmesh.store.db import get_db

async def generate_repomap(project_path: str) -> str:
    """
    Generates a dense, structural map of the repository (AST Repomap).
    Uses the repo_nodes table generated by RepoGraph.
    """
    db = get_db()
    
    # Query all nodes for this project
    # Since we don't have project_path in repo_nodes directly, 
    # we just query all repo_nodes (assuming 1 db per project for now, 
    # as data_dir is usually project-specific or we can filter by file path prefix).
    
    # Fetch all repo nodes
    rows = await db.fetchall("SELECT * FROM repo_nodes ORDER BY file_path, start_line")
    if not rows:
        return "Repository map is empty. The project may not have been indexed yet, or contains no supported code files."

    # Group by file
    files_map = {}
    for row in rows:
        fp = row["file_path"]
        if fp not in files_map:
            files_map[fp] = []
        files_map[fp].append(row)

    # Build the tree string
    lines = ["ContextMesh AST Repository Map:"]
    lines.append("=" * 40)
    
    for fp in sorted(files_map.keys()):
        # Try to make path relative if possible
        try:
            rel_path = str(Path(fp).relative_to(project_path))
        except ValueError:
            rel_path = fp
            
        lines.append(f"\n📄 {rel_path}")
        
        for node in files_map[fp]:
            symbol = node["name"]
            type_ = node["type"].upper()
            line_no = node["start_line"]
            
            if type_ == "CLASS_DEFINITION" or type_ == "CLASS_DECLARATION":
                lines.append(f"  📦 class {symbol} (Line {line_no})")
            elif type_ in ("FUNCTION_DEFINITION", "FUNCTION_DECLARATION", "METHOD_DEFINITION", "METHOD_DECLARATION"):
                lines.append(f"  ⚡ function {symbol} (Line {line_no})")
            else:
                lines.append(f"  • {type_}: {symbol} (Line {line_no})")

    lines.append("\n" + "=" * 40)
    lines.append("Use this structural map to understand the architecture. To view the full body of any function or class, use your file reading tools on the specified file and line numbers.")
    
    return "\n".join(lines)
